### ISSUE TITLE
Ryven webside

### ISSUE THREAD

**Issue by vkuehn** [leon-thomm/Ryven#111]
Looks like the README.md does link to https://github.com/leon-thomm/ryven-website which doesn't exist anymore.

Not sure how the webside is now created but it's wrong.

However replacing the QT Frontend with something web based would be greatly appreciated

**Comment by leon-thomm** [comment]
Sorry, I'm restructuring the repository right now because the website itself never received a contribution. `ryven-website` is now private, there will be a new repo that only contains the guide for the website. However, the repo only hosted the sources for https://ryven.org which does not provide a web interface for Ryven.

**Comment by vkuehn** [comment]
ok thanks for the clarification
