### ISSUE TITLE
Pypi release for arg parser?

### ISSUE THREAD

**Issue by kevinlinxc** [leon-thomm/Ryven#133]
It seems like there are lot of nice features introduced with the arg parser which is now in the dev branch. Will these be released to Pypi? Do you need help with anything?

**Comment by leon-thomm** [comment]
Hey, yes the command line arguments are almost ready for publish. The progress in this repo was halted for a while due to issues including a copyright disagreement. Meanwhile, I am confident that the way I decided to manage copyright-, authorship- and acknowledgement notices is in accordance with the law and the spirit of the project. After that I was quite busy over the past months and mainly worked on ryvencore.

The code of the dev version is mostly ready, all major features are implemented by now. Before publishing someone should

- do some more manual testing
- make sure all versions are changed accordingly (also in ryvencore-qt), presumably to v3.2 for Ryven. v0.3.2 for ryvencore-qt, dependency to ryvencore v0.3.* (*not* v0.4)
- work over the README again

Feel free to open PR. The next big step after that would be ryvencore v0.4 compatibility but this can be part of a later release (#126).

**Comment by leon-thomm** [comment]
this has been done [a while ago](https://github.com/leon-thomm/Ryven/releases/tag/v3.4.0), closing this issue
