### ISSUE TITLE
I would like to add the Arabic language to your project

### ISSUE THREAD

**Issue by asgore-undertale** [leon-thomm/Ryven#21]
Heya,
I actually have no issue, I saw your project and I did like it, and I would like to add the Arabic language. =)

**Comment by leon-thomm** [comment]
Well, that's interesting. However, I feel like the tradeoff would not be worth it. I am trying to keep Ryven's implementation as transparent and simple as possible. That's the only reason why stuff like Ryven Console is even possible, because I keep the core simple and therefore can build anything on top of it.
The labels in the Ryven applications are partly defined by automatically generated ui files, and partly programatically, dynamically created in the code. Introducing language packs would therefore complicate things _a lot_, which is why I am reluctant. If you disagree, please elaborate your ideas further :)

**Comment by asgore-undertale** [comment]
hmmm... Well, You worked on the project And sure you are the one who know what is better for it.
I will be there if you decide to add language packs in the futur.
Goodluck.
hopfulling to see your project bigger and bigger. =)
(and sorry for my English)

**Comment by leon-thomm** [comment]
Thanks for the support!
