### ISSUE TITLE
main_widget used in console and project structure

### ISSUE THREAD

**Issue by asdMild** [leon-thomm/Ryven#46]
1.the first issue is that i use the ryven_console, and i use a lot of self.main_widget to get the text from widget, and it list the error:

LogPython: EXCEPTION in
LogPython: UE4ActorClass
LogPython: 'function' object has no attribute 'currentText'
LogPython: 'NoneType' object is not iterable
LogPython: EXCEPTION in
LogPython: UE4ActorClass
LogPython: 'function' object has no attribute 'currentText'
LogPython: 'NoneType' object is not iterable
LogPython: EXCEPTION in
LogPython: UE4GetMap
LogPython: 'function' object has no attribute 'currentText'
LogPython: EXCEPTION in
LogPython: UE4ActorClass
LogPython: 'function' object has no attribute 'currentText'
LogPython: 'NoneType' object is not iterable
LogPython: The flow has been successfully created. What to do next?

the main_widget called from node_instance is not current in ryven_console, but work well in Ryven.、
i decouple the node_instance and main_widget by setting the parameters of node_instance by main_widget, not get from main_widget anymore.

2.and the other thing is that the project file has a lot of Repeated class naming, like 'flow',
the class of flow is different in both ryven and ryven_console, but the name is the same,  
i can run each of them safely in different application-loop, but it is hard to run both in one remain app-loop.

and also there is a lot of Relative path which is base on the path of application running from, it is more safely if it was base on the 

`os.path.split(__file__)[0],` which is the path of the current module.  

all above has be fixed by myself,
and i see your are in plan of Ryven3, maybe these can be changed in the future

**Comment by leon-thomm** [comment]
I can give a seak peek at the system in Ryven 3 now, regarding this. Tldr: all those issues are non existent there anymore, due to a better overall system.
1. when running a project in ryven console, the point is to have no GUI, so ofc there does not exist a `main_wiget`. Ryven 3 will support you in programming your nodes in a way that they are not dependent on your GUI (they never should be).
2. yeah, the ryven console thing was a completely separate application. In Ryven 3 it won't be, you will run your project directly on the back end using the API, so it runs exactly what is running in the normal Ryven editor, just without the front end. Therefore you can even perform all possible modifications (like adding/removing/connecting/disconnecting nodes, creating/changing vars and so on) directly from the console

**Comment by leon-thomm** [comment]
As announced, you shouldn't run into these issues with [Ryven 3](https://github.com/leon-thomm/Ryven/releases/tag/v3.0.0-alpha) anymore. Assuming you wrote your nodes corrently according to the [Ryven 3 guide](https://ryven.org/guides.html#/), all your nodes should be automatically compatible with Ryven Console, as Ryven is now based on [`ryvencore-qt`](https://github.com/leon-thomm/ryvencore-qt) (all frontend stuff here) and `ryvencore` (backend, all functionality here). Ryven Console does nothing but run your project on the backend (`ryvencore`) now. You can run Ryven Console via `python Ryven.py console`
