### ISSUE TITLE
Where are UI files for Qt Designer?

### ISSUE THREAD

**Issue by GiovanniGrieco** [leon-thomm/Ryven#52]
Hi,
I'm trying to understand your code and there are some UI files that report a header like this:
```
################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
```

Still, it seems these UI files are not in this repository. Where do I find them?

Thank you,
Giovanni

**Comment by leon-thomm** [comment]
the xml ui files are not in the repo, but they contain only the topmost layouts, one or two widget placeholders and the menu items (which are extended and connected in MainWindow.py) so they aren't really important. Almost all UI is created in code. I should probably add them to the ui folder though.

sorry, the code of Ryven master is a bit messy rn and in the next version the structure will be quite different. The dev branch already doesn't contain the core anymore, since, as I announced in #50, it will become a library soon. For understanding the software, the library will be much better I think. The next Ryven version will take some more time probably to finish, because of all the changes.

**Comment by leon-thomm** [comment]
added [here](https://github.com/leon-thomm/Ryven/tree/master/Ryven/src/uic)
