### ISSUE TITLE
Error loading file with rounded slider widget

### ISSUE THREAD

**Issue by Tanneguydv** [leon-thomm/Ryven#76]
Hello,
when I load a `*.json` project file where a slider with its "round" checkbox checked is inside, I get this error :

`OSError : could not  find class definition`

Also  : I can't set the slider to more than 99, how can we change it? I tried to look to its definition (widget and node) without success...

**Comment by leon-thomm** [comment]
thanks!

I corrently cannot reproduce this on my machine. Are you running Ryven from master branch? Which ryvencore-qt version do you use (you can see by executing command `pip list` or `pip freeze`) ?

The limit of the scale checkbox is intentional. If you want to use higher scales, I suggest you plug in a val node to the `scl` input instead.

**Comment by Tanneguydv** [comment]
My bad, it was an error from my own `nodes.py` definition.
I've used your` Val_Node` as a template for one of my own but I've forgotten to create a `widgets.py` file and import it.
So it all ended with `OSError : could not find class definition` ... !

Thank you for the tip about `scl` input !
